"""celulares

Revision ID: 54fc94b2bb45
Revises: 
Create Date: 2024-11-13 16:30:06.183697

"""
from werkzeug.security import generate_password_hash
from models import User
from app import db
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54fc94b2bb45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('almacenamiento', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('bateria', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('stock', sa.String(length=3), nullable=False),
    sa.Column('imei', sa.String(length=100), nullable=False),
    sa.Column('accesorio', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    existing_user = User.query.filter_by(username='admin').first()

    if not existing_user:
        admin_user = User(
            username='admin',
            password_hash = generate_password_hash('admin'),
            is_admin=True,
        )
        db.session.add(admin_user)
        db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('equipo')
    # ### end Alembic commands ###
